mlflow:
  experiment_name: "fraud_detection_v1"
  register_model_name: "fraud_detection"
  tracking_uri: "http://mlflow-server:5500"
  artifact_location: "s3://mlflow/fraud_detection"
  s3_endpoint_url: "http://minio:9000"
  bucket: "mlflow"

kafka:
  bootstrap_servers: "kafka-1:29092,kafka-2:29092,kafka-3:29092"
  username: "kafka-user"
  password: "kafka-1234-password"
  topic: "transactions"
  output_topic: "fraud_predictions"

training_data:
  source_bucket: transactions
  destination_bucket: fraud-features
  lookback_days: 30
  minimum_rows: 10000
  label_column: is_fraud
  dataset_version: v1
  
# model:


# features:


# spark:

